name: Mon Flux de travail

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de la branche
        uses: actions/checkout@v3
        with:
           ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup PHP Je met la même version que celle du serveur
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.14
      - name: Pull de la branche
        run: |
          git pull origin main
          composer install --ignore-platform-reqs
      - name: Mise à jour de la branche main
        run: |
          git pull origin main
          php bin/console doctrine:schema:update --force
          git push
      - name: Clear cache
        run: rm -rf var/cache/*
    env:
      COMPOSER_PHP: "8.1.14"
      DATABASE_URL: ${{secrets.DATABASE_URL}}
